### ISSUE TITLE
Uncaught exception when reading a plist with a missing key value

### ISSUE THREAD

**Issue by madig** [unified-font-object/ufoLib#140]
1. Get [test.ufo.zip](https://github.com/unified-font-object/ufoLib/files/1963269/test.ufo.zip)
2. `fontmake -u test.ufo -o ttf` (Python 3.6)
```
INFO:fontmake.font_project:Building TTFs
INFO:fontmake.font_project:Decomposing glyphs for sdsd-sdsdd
Traceback (most recent call last):
  File "c:\program files\python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\program files\python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Program Files\Python36\Scripts\fontmake.exe\__main__.py", line 9, in <module>
  File "c:\program files\python36\lib\site-packages\fontmake\__main__.py", line 226, in main
    ufo_paths, is_instance=args.pop('masters_as_instances'), **args)
  File "c:\program files\python36\lib\site-packages\fontmake\font_project.py", line 525, in run_from_ufos
    **kwargs)
  File "c:\program files\python36\lib\site-packages\fontmake\font_project.py", line 219, in build_ttfs
    self.decompose_glyphs(ufos, glyph_filter=lambda g: g)
  File "C:\Users\nikolaus.waxweiler\AppData\Local\Python\Python36\site-packages\fontTools\misc\loggingTools.py", line 372, in wrapper
    return func(*args, **kwds)
  File "c:\program files\python36\lib\site-packages\fontmake\font_project.py", line 158, in decompose_glyphs
    for glyph in ufo:
  File "c:\program files\python36\lib\site-packages\defcon\objects\font.py", line 220, in __iter__
    yield self._glyphSet[name]
  File "c:\program files\python36\lib\site-packages\defcon\objects\layer.py", line 261, in __getitem__
    self.loadGlyph(name)
  File "c:\program files\python36\lib\site-packages\defcon\objects\layer.py", line 186, in loadGlyph
    self._glyphSet.readGlyph(glyphName=name, glyphObject=glyph, pointPen=pointPen)
  File "C:\Users\nikolaus.waxweiler\AppData\Local\Python\Python36\site-packages\ufoLib\glifLib.py", line 304, in readGlyph
    _readGlyphFromTree(tree, glyphObject, pointPen, formatVersions=formatVersions)
  File "C:\Users\nikolaus.waxweiler\AppData\Local\Python\Python36\site-packages\ufoLib\glifLib.py", line 838, in _readGlyphFromTree
    _readGlyphFromTreeFormat2(tree=tree, glyphObject=glyphObject, pointPen=pointPen)
  File "C:\Users\nikolaus.waxweiler\AppData\Local\Python\Python36\site-packages\ufoLib\glifLib.py", line 955, in _readGlyphFromTreeFormat2
    _readLib(glyphObject, element)
  File "C:\Users\nikolaus.waxweiler\AppData\Local\Python\Python36\site-packages\ufoLib\glifLib.py", line 993, in _readLib
    plist = readPlistFromTree(child)
  File "C:\Users\nikolaus.waxweiler\AppData\Local\Python\Python36\site-packages\ufoLib\plistFromETree.py", line 12, in readPlistFromTree
    return parser.parseTree(tree)
  File "C:\Users\nikolaus.waxweiler\AppData\Local\Python\Python36\site-packages\ufoLib\plistFromETree.py", line 18, in parseTree
    self.parseElement(tree)
  File "C:\Users\nikolaus.waxweiler\AppData\Local\Python\Python36\site-packages\ufoLib\plistFromETree.py", line 25, in parseElement
    self.parseElement(child)
  File "C:\Users\nikolaus.waxweiler\AppData\Local\Python\Python36\site-packages\ufoLib\plistFromETree.py", line 25, in parseElement
    self.parseElement(child)
  File "C:\Users\nikolaus.waxweiler\AppData\Local\Python\Python36\site-packages\ufoLib\plistFromETree.py", line 30, in parseElement
    self.handleEndElement(element.tag)
  File "C:\Users\nikolaus.waxweiler\AppData\Local\Python\Python36\site-packages\ufoLib\plistlib.py", line 48, in handleEndElement
    super().handle_end_element(*args, **kwargs)
  File "c:\program files\python36\lib\plistlib.py", line 337, in handle_end_element
    handler()
  File "c:\program files\python36\lib\plistlib.py", line 373, in end_dict
    (self.current_key,self.parser.CurrentLineNumber))
AttributeError: 'PlistTreeParser' object has no attribute 'parser'
```
The error is a missing value for a key in A_.glif; reading the file with plistlib directly causes this error:
```
>>> plistlib.readPlist("test.ufo/glyphs/A_.glif")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Program Files\Python36\lib\plistlib.py", line 164, in readPlist
    dict_type=_InternalDict)
  File "C:\Program Files\Python36\lib\plistlib.py", line 1015, in load
    return p.parse(fp)
  File "C:\Program Files\Python36\lib\plistlib.py", line 325, in parse
    self.parser.ParseFile(fileobj)
  File "..\Modules\pyexpat.c", line 468, in EndElement
  File "C:\Program Files\Python36\lib\plistlib.py", line 337, in handle_end_element
    handler()
  File "C:\Program Files\Python36\lib\plistlib.py", line 373, in end_dict
    (self.current_key,self.parser.CurrentLineNumber))
ValueError: missing value for key 'type' at line 33
```

**Comment by madig** [comment]
The problem seems to be that plistlib is set up to parse a .plist itself instead of handling an already parsed tree object, so it assumes that parse() must have been called. I suppose I can insert a fake `self.parser` that always returns line 0? Then the ValueError has to be caught and the plist regarded as invalid.

**Comment by typesupply** [comment]
I've reviewed the PR and it seems fine for >= 3.1. I have no idea how to handle this in earlier Pythons. I don't think we should copy source code into our tree.

**Comment by madig** [comment]
We could drop support for <= 3.1 😁

**Comment by anthrotype** [comment]
> Thanks! Does this then close #140?

@benkiel this is the error we get now with ufoLib 2.3.0 with the test.ufo in question:

```
$ fontmake -u '/home/clupo/Downloads/test.ufo (1)/test.ufo' -o ttf --output-dir '/home/clupo/Downloads/test.ufo (1)/' 
INFO:fontmake.font_project:Building TTF for sdsd-sdsdd
INFO:ufo2ft:Pre-processing glyphs
Traceback (most recent call last):
[...]
  File "ufoLib/plistlib.py", line 153, in end_dict
    raise ValueError("missing value for key '%s'" % self.current_key)
ValueError: missing value for key 'type'
```

I believe this is acceptable.

**Comment by anthrotype** [comment]
well at least we get the same error message for both py2 and py3 now since they both use the same `ufoLib.plistlib` implementation instead of the stdlib one.

you may have noticed that, unlike the stdlib module, the line number is now missing in our new implementation... :grin: 

Turns out that the ["target-parser" interface](http://lxml.de/parsing.html#the-target-parser-interface) we are currently using to directly build property list objects from XML data doesn't provide us with a line number that we can use in the error message.

With lxml parsed Element objects do have a `sourceline` attribute, but... `xml.etree` does not give us that.
And also, we are not building a tree of Element objects and then transform that into plist structure (dict, list, string, etc.), but we are creating the latter directly as we parse, so even if we were only supporting the lxml backend, we wouldn't have access to `sourceline` (as we don't create Elements).

Sorry, I think we can't much more about giving better error messages for malformed property lists :(

**Comment by benkiel** [comment]
We catch it now, in Py2 and Py3, I think we can close this then. Line numbers would be nice, but at least the error is caught.
