### ISSUE TITLE
Missing kerningValidatorReportPairs

### ISSUE THREAD

**Issue by LettError** [unified-font-object/ufoLib#22]
I'm missing ```kerningValidatorReportPairs(kerning, groups)```

**Comment by typesupply** [comment]
There's no such thing as a conflict anymore so that validation went away. [See here](https://github.com/unified-font-object/ufo-spec/issues/27).

**Comment by adrientetar** [comment]
I think Erik may be talking of this:

```
Traceback (most recent call last):
  File "c:\users\admin\downloads\defconqt\lib\defconQt\controls\glyphLineView.py", line 975, in setGlyphRecords
    self._unsubscribeFromGlyphs()
  File "c:\users\admin\downloads\defconqt\lib\defconQt\controls\glyphLineView.py", line 879, in _unsubscribeFromGlyphs
    font.kerning.removeObserver(self, "Kerning.Changed")
  File "c:\users\admin\downloads\defcon\lib\defcon\objects\font.py", line 441, in _get_kerning
    self._loadKerningAndGroups()
  File "c:\users\admin\downloads\defcon\lib\defcon\objects\font.py", line 391, in _loadKerningAndGroups
    kerningValidity, kerningErrors = kerningValidator(kerning, groups)
TypeError: kerningValidator() takes 1 positional argument but 2 were given
```

But it's more of a defcon issue, it wasn't updated to follow the API change.

**Comment by LettError** [comment]
Sorted. The kerning validation has been removed from MutatorMath, the import is no longer necessary. Thanks.
